### ISSUE TITLE
Error when trying to import dippykit on colab

### ISSUE THREAD

**Issue by ThinkSpid** [dippykit/dippykit#1]
When i try to import dippykit on colab to do the processing on colab i have some error like this:
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-1-7ef72003aec5> in <module>()
      1 import matplotlib
----> 2 matplotlib.use("TkAgg")
      3 import matplotlib.pyplot as plt

1 frames
/usr/local/lib/python3.6/dist-packages/matplotlib/pyplot.py in switch_backend(newbackend)
    220                 "Cannot load backend {!r} which requires the {!r} interactive "
    221                 "framework, as {!r} is currently running".format(
--> 222                     newbackend, required_framework, current_framework))
    223 
    224     rcParams['backend'] = rcParamsDefault['backend'] = newbackend

ImportError: Cannot load backend 'TkAgg' which requires the 'tk' interactive framework, as 'headless' is currently running

---------------------------------------------------------------------------
NOTE: If your import is failing due to a missing package, you can
manually install dependencies using either !pip or !apt.

To view examples of installing some common dependencies, click the
"Open Examples" button below.
---------------------------------------------------------------------------

I am using 
`!pip install dippykit`
to install dippykit on colab

**Comment by motazalfarraj** [comment]
Thanks for letting us know about this issue. 
We have just pushed an update to fix this bug.  Installing dippykit 2.0.3 using pip should fix this problem.
